source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SwiftPhotoGallery_Example' do
  pod "SwiftPhotoGallery", :path => "../"
end

target 'SwiftPhotoGallery_Tests' do
  pod "SwiftPhotoGallery", :path => "../"
  pod 'Nimble', '~> 5.0.0'
end

