platform :ios, '8.3'
use_frameworks!
inhibit_all_warnings!

target 'SwiftPhotoGallery_Example' do
  pod "SwiftPhotoGallery", :path => "../"
  pod 'pop',                          '~> 1.0' 
end

target 'SwiftPhotoGallery_Tests' do
  pod "SwiftPhotoGallery", :path => "../"
  pod 'Nimble', '~> 5.0.0'
end

