source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SwiftPhotoGallery_Example', :exclusive => true do
  pod "SwiftPhotoGallery", :path => "../"
end

target 'SwiftPhotoGallery_Tests', :exclusive => true do
  pod "SwiftPhotoGallery", :path => "../"
  pod 'Nimble', '~> 4.0.0'
end


